### ISSUE TITLE
Is there a more elegant way to send the profile table to the Python environement?

### ISSUE THREAD

**Issue by NBCS1** [haesleinhuepf/napari-plot-profile#12]
First, thanks you, that's a very nice tool!

Otherwise, I wanted to calculated the area under my peaks in a profile (with Python) but I could not find a way to export the profile in my environement. 
Maybe I missed something obvious...
But in the mean time I did something pretty dirty:
I added a new function to your code but I'm not that experienced so there is some part of your code I don't get entirely. At the end this solution took me more time than saving as csv and reopening it...
```
def _list_out(self):
        table = {}
        for my_profile in self.data:
            positions = np.asarray(my_profile['positions'])
            for i, x in enumerate(positions[0]):
                table[my_profile['name'] + '_pos' + str(i)] = positions[:, i]

            table[my_profile['name'] + '_intensity'] = my_profile['intensities']
            table[my_profile['name'] + '_distance'] = my_profile['distances']

        return table
```
It works nice when I plot from the console like:

```
from napari_plot_profile import PlotProfile
profiler = PlotProfile(viewer)
my_profile=profiler._list_out()
```
So I would like your opinion on the matter. 

EDIT: Sorry, nevermind, found it

`my_profile=PlotProfile(viewer).data`

**Comment by haesleinhuepf** [comment]
Hi @NBCS1 ,

just to let you know, with the new release [0.2.0](https://github.com/haesleinhuepf/napari-plot-profile/releases/tag/0.2.0) there is now a `to_table()` function in `ProfilePlot` that allows you to easily create a pandas `DataFrame`, see the [demo notebook](https://github.com/haesleinhuepf/napari-plot-profile/blob/main/docs/demo.ipynb). Furthermore, please note that `profiler.data` is now deprecated and may be removed in a future version.

Let me know if this works for you! I would then close this issue :-)

Thanks for the feedback!

Best,
Robert

**Comment by NBCS1** [comment]
Hi,

Works nice! Thanks

Nelson
