### ISSUE TITLE
Plot not (always) what I expect, plus UI Comments

### ISSUE THREAD

**Issue by psobolewskiPhD** [haesleinhuepf/napari-plot-profile#3]
Awesome plugin—I'd put together something similar using some napari examples and help from napari.zulip, but this is much more polished.
Main comment:
1) Sometimes the plots are not what I expect? See example below:
![image](https://user-images.githubusercontent.com/76622105/130432469-2cf9f760-2bc8-4323-8331-8cfb984c52cc.png)
I think I have the line draw fairly symmetrical and mousing over points returns values that are in agreement with the matplotlib graph my widget generates. But your plugin graph is odd, very asymmetrical and just one peak. Is it not actually doing line profiles but something different? Is it due to the angle, so pixels are not neighboring correctly?
For reference, I'm using `measure.profile_line` from skimage for my plot—again based on napari/examples (my code in gist at bottom, with some comments)

Minor comments:
1) It's cool that the plot lines use the img LUTs, but initially I thought the plugin just didn't work, because my preferred LUT is inverted, so I get black on black.  (You can see the same issue with my matplotlib below: black on black for the case of the text. derp.)
![image](https://user-images.githubusercontent.com/76622105/130430267-fe3a1411-10e5-4128-b883-6b9d9019ab71.png)
Once I figured out it was from the Image LUT, I was again confused because changing the image LUT didn't change the lines color. Eventually I figured out you change the image LUT and then have to go back to the Shapes layer for it to trigger. 
So in the end I think I would prefer the option to use the Shapes line color, since it's more intuitive?
2) On a related note, switching to the image layer makes the graph disappear. This is somewhat odd, because I need to be on the image layer to so the cursor returns values in the status bar.
3) When I draw lines, e.g. below, the plot is reversed. I drew the line from top to bottom so I'd expect the graph to go from start to finish of the line, as in the plot below the image.
![image](https://user-images.githubusercontent.com/76622105/130431400-2a1b9997-8593-4902-baa3-ce46e5011972.png)
4) Sometimes the refresh & live-refresh ceases to work? I think it's with z-slices when I draw on one slice then on another and then go back. I assume the last line is "live" on a different slice, so the earlier one doesn't work. Drawing a new line on the old slice makes it work again... 

Here's a link to my hacked together widget, which should run:
(FYI The examples above were with a different approach where I get the shape layer and slice.)
https://gist.github.com/psobolewskiPhD/53eec7440eda501d9edf08a99659f6b0
Ironically, this example doesn't work with your plugin. Traceback:
<details>
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari_plot_profile/_dock_widget.py", line 101, in _on_selection
    self.redraw(force_redraw=True)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari_plot_profile/_dock_widget.py", line 158, in redraw
    my_profile = profile(layer, line, num_points=num_bins)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari_plot_profile/_dock_widget.py", line 219, in profile
    start = line[min(current_line, len(line) - 1)] / layer.scale
ValueError: operands could not be broadcast together with shapes (2,) (3,) 
</details>
This blocks all interaction with the shapes layer and breaks the plugin. Is there a way to *switch off* a plugin? the [x] just closes it, but it's still listed in the Window menu. 

I think because I take the route of making a 2D generic shapes layer that appears on all slices, since for a "tool" it was more intuitive to me to see a line profile for the same physical line in z or t. It helped get around the issue of having to re-draw a line on a different slice if I didn't delete the previous one. I still want advancing slices to trigger the replotting too...Edit: got it working! updated gist.
Just passing this to napari triggers the traceback:

```
line = np.array([[11, 13], [111, 113]])
line_prof_layer = viewer.add_shapes(
    line, shape_type="line", edge_color="red", name="Line Profile"
)
```

**Comment by haesleinhuepf** [comment]
> Sometimes the plots are not what I expect? See example below:

Hi @psobolewskiPhD ,

thanks for reporting this bug! It looks to me like a scalign issue. Can you share the dataset you were analyzing?

**Comment by psobolewskiPhD** [comment]
It's the Bars-G10-P15-stack.tif from 
http://bigwww.epfl.ch/deconvolution/bars/
(I think I originally got it from clij2-clfft)

**Comment by haesleinhuepf** [comment]
Thanks @psobolewskiPhD , I just created inidividual issues for the things you mentioned. It will be easier to keep track of them. Thanks for your reports!

**Comment by psobolewskiPhD** [comment]
NP, sorry I was writing about the one thing and then added the others—some aren't "issues" or bugs per se, just design decisions, so I wasn't sure if they warranted an "issue".

**Comment by haesleinhuepf** [comment]
I'm just saying it makes sense to have one thread per thing to discuss. I have issues following otherwise ;-)
